services:
    arturdoruch_paginator:
        class: ArturDoruch\PaginatorBundle\Paginator
        arguments: ["%arturdoruch_paginator.limit%"]

    arturdoruch_paginator.twig_extension.pagination:
        class: ArturDoruch\PaginatorBundle\Twig\Extension\PaginationExtension
        arguments: ["@router", "%arturdoruch_paginator.config%"]
        tags:
            - { name: twig.extension }